name: Build and Deploy Vue Application to Github Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build_deploy_vue:
    runs-on: ubuntu-latest
    name: Build and Deploy Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Deploy-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        useyarn: true
        username: 'rame0'
        reponame: 'bonds-filter'
        token: ${{ secrets.GITHUB_TOKEN }} # no need to change this line this is used to create the branch in your application repository
